

def cmp(c):
    if (c == 'A'):
      return 'T'
    if (c ==  'T'):
      return 'A'
    if (c == 'G'):
      return 'C'
    if (c == 'C'):
      return 'G'

def reverse(s):
  result = ""
  for c in s:
    result = cmp(c) + result
  return result



print(reverse('CTCGGCACGTTTAAAAGCAGGGAACATAAGGTCTGTGTGTCGTTTTCGGGATTTCATTGGTAGTACACCAAAGACAACTTGCGGGACGGGTACGCTTAGGATAAACTGCCTATGATCTTAGAAGTCTACCAACCCTTACGCTTACTGCCCCATCACCCCACTGAATGCCCCCCAGCCGTGAAATACAGGTGTATAGATCTTGGCGACTTCCCTTGATGGTTCTGTACCTATGGTTTTGTGGGCCGGCCAAGCGATTGCTGGTAGACAACGTAATAATTGATTATAAACGGGTTGCTAGATTTATGGATTGGATACGGACCGGGGCGACCCCTAGGTGCGTGGTTGACTGTCGTTTAATGGTACAACGGCCTCGTGGTTACTATACTGTTTTGCTCAGCTATCTGATCTTAACCGGACCCTGACTTGGATTTCGTACCTAGTTTGGATCTCTCACGACGCTCGCAGCGATCGCGTCACCGGCAAGACTGTCCATTCAAACCTTTCATCAACTGGCTTCGGGGTGCCGCTTTCTAGGGGTGTGCAATTCCGGAAATCGTGGCTGAGAAGACAACGATGTTAGCACCCGGAACCGCGAACTAGGACGTGGGTCGGCGCAAATAAAGCAGGCGGGACGTTTCAGTCGGGTGGTACGCAATTCCTAGCGGCCCAGCGTAACCACACGGACTGTCAACACCATACGAGTTCAGAAGCGACATAGCTATACCTGGTTGACCCATAAAAGTATTGGCCTGTAACTCCGTCGTCGAGAGGGCCTTCGAATCGGCAGTTTGTGGTGCATCGCGCGCCG'))